[2020-11-02T17:29:20.458] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604309360457
err name: Error
err message: 邮件及时发送 失败
err stack: Error: 邮件及时发送 失败
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:225:9)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
*************** error log end ***************

[2020-11-02T17:39:59.255] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604309999254
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604309973478, end: 1604309995739. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 53 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604309973478, end: 1604309995739. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 53 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:219:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:538:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-02T17:41:30.003] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/mail/postMailToCreate
request client ip:  ::ffff:127.0.0.1
request body: 
{"title":"1","text":"1","allServerTrue":true,"roleId":"","sendTime":true,"mailLink":"2","plaform":"","channel":"","serverName":["测试区服","测试区服四服","测试机一","测试区服三服","测试机一机","测试机二","测试区服二服","测试区服一服"],"carryAnnex":true,"sendDateTime":"","smtpId":"2961","Annex":["{\"ID\":\"9001\",\"name\":\"特殊道具\",\"number\":\"231\"}","{\"ID\":\"17002\",\"name\":\"文物\",\"number\":\"11\"}"],"gameid":"1"}
response time: 1604310090003
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604310064259, end: 1604310086546. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 54 } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604310064259, end: 1604310086546. Message was: {
  module: 'mail',
  mail: 'immediate',
  args: { query: undefined, body: { gameid: '1', id: 54 } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at MailService._callee9$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:219:34)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at MailService.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at MailService.mailSendTimely (H:\致命代码\fancyguo-gm\server\src\app\service\mail.js:538:32)
    at MailService._callee6$ (H:\致命代码\fancyguo-gm\server\src\app\service\/mail.js:192:16)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

[2020-11-02T21:33:15.570] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/white/mailRelatedUser
request client ip:  ::ffff:127.0.0.1
request body: 
{"roleId":[{"serverid":1,"id":1231231},{"serverid":2,"id":5456465},{"serverid":3,"id":9681699},{"serverid":4,"id":13906933},{"serverid":5,"id":18132167},{"serverid":6,"id":22357401},{"serverid":7,"id":26582635},{"serverid":8,"id":30807869},{"serverid":9,"id":35033103},{"serverid":10,"id":39258337},{"serverid":11,"id":43483571},{"serverid":12,"id":47708805},{"serverid":13,"id":51934039},{"serverid":14,"id":56159273},{"serverid":15,"id":60384507},{"serverid":16,"id":64609741},{"serverid":17,"id":68834975},{"serverid":18,"id":73060209},{"serverid":19,"id":77285443},{"serverid":20,"id":81510677},{"serverid":21,"id":85735911},{"serverid":22,"id":89961145},{"serverid":23,"id":94186379},{"serverid":24,"id":98411613},{"serverid":25,"id":102636847},{"serverid":26,"id":106862081},{"serverid":27,"id":111087315},{"serverid":28,"id":115312549},{"serverid":29,"id":23},{"serverid":30,"id":31},{"serverid":31,"id":2312},{"serverid":32,"id":123},{"serverid":33,"id":1},{"serverid":34,"id":12313},{"serverid":35,"id":23},{"serverid":36,"id":2321},{"serverid":37,"id":31231},{"serverid":38,"id":123},{"serverid":39,"id":312},{"serverid":40,"id":23},{"serverid":41,"id":12},{"serverid":42,"id":1212312313},{"serverid":43,"id":23},{"serverid":44,"id":23},{"serverid":45,"id":23},{"serverid":46,"id":12},{"serverid":47,"id":31231},{"serverid":48,"id":123},{"serverid":49,"id":12312},{"serverid":50,"id":12},{"serverid":51,"id":31},{"serverid":52,"id":123},{"serverid":53,"id":31231},{"serverid":54,"id":231},{"serverid":55,"id":23},{"serverid":56,"id":12},{"serverid":57,"id":312},{"serverid":58,"id":2312}],"name":"没什么问题","type":false,"notebook":"123","gameid":"1"}
response time: 1604323995570
err name: Error
err message: connect ECONNREFUSED 127.0.0.1:5000
err stack: Error: connect ECONNREFUSED 127.0.0.1:5000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
*************** error log end ***************

[2020-11-02T21:36:14.311] [ERROR] errorLogger - 
*************** error log start ***************
request method: POST
request originalUrl:  /api/white/mailRelatedUser
request client ip:  ::ffff:127.0.0.1
request body: 
{"roleId":[{"serverid":1,"id":1231231},{"serverid":2,"id":5456465},{"serverid":3,"id":9681699},{"serverid":4,"id":13906933},{"serverid":5,"id":18132167},{"serverid":6,"id":22357401},{"serverid":7,"id":26582635},{"serverid":8,"id":30807869},{"serverid":9,"id":35033103},{"serverid":10,"id":39258337},{"serverid":11,"id":43483571},{"serverid":12,"id":47708805},{"serverid":13,"id":51934039},{"serverid":14,"id":56159273},{"serverid":15,"id":60384507},{"serverid":16,"id":64609741},{"serverid":17,"id":68834975},{"serverid":18,"id":73060209},{"serverid":19,"id":77285443},{"serverid":20,"id":81510677},{"serverid":21,"id":85735911},{"serverid":22,"id":89961145},{"serverid":23,"id":94186379},{"serverid":24,"id":98411613},{"serverid":25,"id":102636847},{"serverid":26,"id":106862081},{"serverid":27,"id":111087315},{"serverid":28,"id":115312549},{"serverid":29,"id":23},{"serverid":30,"id":31},{"serverid":31,"id":2312},{"serverid":32,"id":123},{"serverid":33,"id":1},{"serverid":34,"id":12313},{"serverid":35,"id":23},{"serverid":36,"id":2321},{"serverid":37,"id":31231},{"serverid":38,"id":123},{"serverid":39,"id":312},{"serverid":40,"id":23},{"serverid":41,"id":12},{"serverid":42,"id":1212312313},{"serverid":43,"id":23},{"serverid":44,"id":23},{"serverid":45,"id":23},{"serverid":46,"id":12},{"serverid":47,"id":31231},{"serverid":48,"id":123},{"serverid":49,"id":12312},{"serverid":50,"id":12},{"serverid":51,"id":31},{"serverid":52,"id":123},{"serverid":53,"id":31231},{"serverid":54,"id":231},{"serverid":55,"id":23},{"serverid":56,"id":12},{"serverid":57,"id":312},{"serverid":58,"id":2312}],"name":"没什么问题","type":false,"notebook":"123","gameid":"1"}
response time: 1604324174310
err name: Error
err message: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604324147328, end: 1604324169640. Message was: {
  module: 'white',
  white: 'create',
  args: { query: undefined, body: { id: 13, gameid: '1' } }
}.
err stack: Error: seneca: [TIMEOUT] Action  timed out. Timeout was: 22222 (start: 1604324147328, end: 1604324169640. Message was: {
  module: 'white',
  white: 'create',
  args: { query: undefined, body: { id: 13, gameid: '1' } }
}.
    at Object.errormaker (H:\致命代码\fancyguo-gm\server\node_modules\eraro\eraro.js:112:15)
    at Object.act_tm [as ontm] (H:\致命代码\fancyguo-gm\server\node_modules\seneca\lib\act.js:86:32)
    at Timeout.timeout_check [as _onTimeout] (H:\致命代码\fancyguo-gm\server\node_modules\gate-executor\gate-executor.js:207:16)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
From previous event:
    at SenecaClient._callee$ (H:\致命代码\fancyguo-gm\server\src\xiaolu\/senecaclient.js:16:21)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at SenecaClient.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at SenecaClient.get (H:\致命代码\fancyguo-gm\server\src\xiaolu\senecaclient.js:86:21)
    at whiteServer._callee11$ (H:\致命代码\fancyguo-gm\server\src\app\service\/white.js:209:37)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
    at H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at whiteServer.<anonymous> (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:21:12)
    at whiteServer.sendWhiteMail (H:\致命代码\fancyguo-gm\server\src\app\service\white.js:585:31)
    at whiteServer._callee7$ (H:\致命代码\fancyguo-gm\server\src\app\service\/white.js:154:14)
    at tryCatch (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:45:40)
    at Generator.invoke [as _invoke] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:281:22)
    at Generator.prototype.<computed> [as next] (H:\致命代码\fancyguo-gm\server\node_modules\regenerator-runtime\runtime.js:106:21)
    at asyncGeneratorStep (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (H:\致命代码\fancyguo-gm\server\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9)
*************** error log end ***************

